### ISSUE TITLE
macOS 无法编译

### ISSUE THREAD

**Issue by nuomi1** [Cay-Zhang/RSSBud#1]
目前的配置，在 target 为 Mac 时会失败，因为没有隐式导入 UIKit 框架。

---

Platform: DTK
macOS: 11.0 Beta (20A5343i)
Xcode: 12.0 beta 4 (12A8179i)

**Comment by Cay-Zhang** [comment]
@nuomi1 不好意思，现在问题出在 UI/NSViewRepresentable和UI/NSColor上。其实不难解决，但是我正在考虑RSSBud支持macOS是否真的有必要。

**Comment by Cay-Zhang** [comment]
[v2](https://apps.apple.com/cn/app/rssbud/id1531443645) 已支持 Apple Silicon Macs。
