### ISSUE TITLE
NetNewsWire 支持

### ISSUE THREAD

**Issue by ding667** [Cay-Zhang/RSSBud#12]
这是一款很棒的免费rss阅读器，如果能做一键订阅就太好了。

**Comment by Cay-Zhang** [comment]
Marked

**Comment by Cay-Zhang** [comment]
貌似 NetNewsWire 目前还没有独立的 URL Scheme 可以用来订阅 RSS 源

但 NetNewsWire 支持 feed 协议，你可以在快速订阅中选择 Default 来让 RSSBud 使用该协议（但如果 Default 打开的不是 NetNewsWire 而是一个其他的 App，你就得把那个 App 卸了，因为 iOS 没有方法设置谁来开这个 URL Scheme 🤷‍♂️）
