### ISSUE TITLE
阿里云盘分享链接导入RSSBud后会在后面带上%3F（即“？”）导致导入失败

### ISSUE THREAD

**Issue by HaodongZou** [Cay-Zhang/RSSBud#26]
读取链接正常，但是从RSSHub源添加订阅到rss阅读软件时需要在rss阅读软件中手动删除链接后面的“%3F”（即URL Encode之后的“？”）

例如阿里云分享链接：https://www.aliyundrive.com/s/u5xCrzpMY1z/folder/63203ef3a4931f1a4b6c4820a05be309fcc9a592
导入RSSHub之后得到的rss订阅：http://xx.xx.xx.xx:xx/aliyundrive/files/u5xCrzpMY1z/63203ef3a4931f1a4b6c4820a05be309fcc9a592%3F

**Comment by Cay-Zhang** [comment]
你用的是什么是版本？开发版貌似没有这个问题

**Comment by HaodongZou** [comment]
App Store下载的版本
