### ISSUE TITLE
"Submit new rules" link is corrupted

### ISSUE THREAD

**Issue by Bubbu0129** [Cay-Zhang/RSSBud#30]
在主页面上，**Submit New Rules**的链接指向了`https://docs.rsshub.app/joinus/#ti-jiao-xin-de-rsshub-radar-gui-ze`，本应是`https://docs.rsshub.app/joinus/quick-start.html#ti-jiao-xin-de-rsshub-radar-gui-ze`。
问题似乎出在 [Here](https://github.com/Cay-Zhang/RSSBud/blob/b7364352e57c5ea38731b43005750980f2453478/Shared/OnboardingView.swift#L330)。

**Comment by Cay-Zhang** [comment]
已经在 https://github.com/Cay-Zhang/RSSBud/commit/fb499807e1e3139a0327dab1e8d653c4c0723505 中修改了，但是 v2 还没上 App Store
（你指出的那个按钮一直是禁用状态，实际的 **Submit New Rules** 按钮在上面）
