### ISSUE TITLE
请问低版本iOS有没有可用的替代品？

### ISSUE THREAD

**Issue by geol** [Cay-Zhang/RSSBud#32]
iOS 13.5，已越狱，Appstore里无法下载RSSBud。

**Comment by Cay-Zhang** [comment]
据我所知 RSSBud 是 App Store 上唯一一个能检测 RSSHub 源的 App。[RSSAid](https://github.com/LeetaoGoooo/RSSAid) 是 Flutter App，可以试试自行编译在 iOS 上运行。实在不行可以用捷径解决常用的路由。
