### ISSUE TITLE
一键订阅增加支持pocket cast 这种泛用型播客客户端

### ISSUE THREAD

**Issue by Nergrove** [Cay-Zhang/RSSBud#9]
一键订阅支持一下pocket cast，因为我会用rsshub 订阅喜马拉雅的频道。rssbud能识别喜马拉雅，但是不能订阅到pocketcast。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Cay-Zhang** [comment]
[捷径工坊](https://github.com/Cay-Zhang/RSSBud/blob/main/README.zh-CN.md#%E6%8D%B7%E5%BE%84%E5%B7%A5%E5%9D%8A) 中已有 [订阅到 Pocket Casts 的捷径](https://www.icloud.com/shortcuts/1eb2893bd14743f3a85db1a8f1aa43c3)
